#include "plankbase.h"
#include "readinput.h"
#include "oneelectron.h"
#include "mathlib.h"

// Written By 	: Hemanth Haridas (hemanthhari23@gmail.com)
// version	: 0.0.1
//
// This is the main enrty point to the plank2 code. This file must only contain the base function calls, with every other function
// declarations and definitions placed in the corresponding header and cpp files. This ensures that the main file remains clean in
// an event of a complete rewrite of the code in future.
//

int main(int argc, const char* argv[]) {
	plankbase Molecule;			// Instance of the plank2 executable (Molecule Object)
	std::string fileName = "input.tmp";	// Hardcoded filename => This file is generated by the plank2 code.
	readInput(&Molecule, fileName);

	double tmp = overlapShells(&Molecule, 0, 5);
	return 0;
}
